# yaml-language-server: $schema=schema.json
users:
  - id: admin
    email: admin@dmun.de
    familyName: Doe
    givenName: John
    locale: en
    preferredUsername: admin
    conferenceUserType: ADMIN
  - id: user
    email: user@dmun.de
    familyName: Doe
    givenName: Jane
    locale: en
    preferredUsername: user
    conferenceUserType: TEAM
conferences:
  - title: Dev Conference
    pressWebsite: 'https://devconf.com'
    conferenceUsers:
      - userId: admin
        conferenceUserType: ADMIN
      - userId: user
        conferenceUserType: TEAM
    customRepresentations:
      - name: General Secretary
        type: UN
      - name: ICRC
        type: NSA
        faIcon: kit-medical
    committees:
      - name: General Assembly
        abbreviation: GV
        agendaItems:
          - title: Boosting climate adaptation financing
            active: true
          - title: Promoting inclusive multilateralism
        countries:
          - AF
          - AO
          - AL
          - AD
          - AE
          - AR
          - AM
          - AG
          - AU
          - AT
          - AZ
          - BI
          - BE
          - BJ
          - BF
          - BD
          - BG
          - BH
          - BS
          - BA
          - BY
          - BZ
          - BO
          - BR
          - BB
          - BN
          - BT
          - BW
          - CF
          - CA
          - CH
          - CL
          - CN
          - CI
          - CM
          - CD
          - CG
          - CO
          - KM
          - CV
          - CR
          - CU
          - CY
          - CZ
          - DE
          - DJ
          - DM
          - DK
          - DO
          - DZ
          - EC
          - EG
          - ER
          - ES
          - EE
          - ET
          - FI
          - FJ
          - FR
          - FM
          - GA
          - GB
          - GE
          - GH
          - GN
          - GM
          - GW
          - GQ
          - GR
          - GD
          - GT
          - GY
          - HN
          - HR
          - HT
          - HU
          - ID
          - IN
          - IE
          - IR
          - IQ
          - IS
          - IL
          - IT
          - JM
          - JO
          - JP
          - KZ
          - KE
          - KG
          - KH
          - KI
          - KN
          - KR
          - KW
          - LA
          - LB
          - LR
          - LY
          - LC
          - LI
          - LK
          - LS
          - LT
          - LU
          - LV
          - MA
          - MC
          - MD
          - MG
          - MV
          - MX
          - MH
          - MK
          - ML
          - MT
          - MM
          - ME
          - MN
          - MZ
          - MR
          - MU
          - MW
          - MY
          - NA
          - NE
          - NG
          - NI
          - NL
          - NO
          - NP
          - NR
          - NZ
          - OM
          - PK
          - PA
          - PE
          - PH
          - PW
          - PG
          - PL
          - KP
          - PT
          - PY
          - QA
          - RO
          - RU
          - RW
          - SA
          - SD
          - SN
          - SG
          - SB
          - SL
          - SV
          - SM
          - SO
          - RS
          - SS
          - ST
          - SR
          - SK
          - SI
          - SE
          - SZ
          - SC
          - SY
          - TD
          - TG
          - TH
          - TJ
          - TM
          - TL
          - TO
          - TT
          - TN
          - TR
          - TV
          - TZ
          - UG
          - UA
          - UY
          - US
          - UZ
          - VA
          - VC
          - VE
          - VN
          - VU
          - WS
          - YE
          - ZA
          - ZM
          - ZW

      - name: Security Council
        abbreviation: SC
        agendaItems:
          - title: Addressing conflict root causes
          - title: Examining tech's impact on peace
            active: true
        countries:
          - cn
          - us
          - ru
          - fr
          - gb
          - dz
          - gy
          - kr
          - sl
          - si
          - pk
          - so
          - pa
          - dk
          - gr
